name : Multi-version Node-js environment
on : 
  push : 
    branches : ["master"]
  
  pull_request : 
    branches : ["master"]  
jobs:
  message:
    runs-on : [ubuntu-latest]
    strategy : 
      matrix : 
        version : [12,14,16]
    steps :
    - uses : actions/checkout@v3
      name : Setup JS environment
      
    - uses : actions/setup-node@v3
      with : 
        node-version : ${{matrix.version}}
        
    - run : echo "hello abc"
    
      name : checking npm version.
    - run : npm -v


      
