name : Multi-version Node-js environment
on : 
  push : 
    branches : ["master"]
  
  pull_request : 
    branches : ["master"]  
jobs:
  message:
    runs-on : [ubuntu-latest]
    steps :
    - uses : actions/checkout@v3


      
