name: Testing DOtnet environment 

on:
  workflow_dispatch: 

jobs:
  prints:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
      name: dotnet installation
    - uses: actions/setup-dotnet@v2
      with:
        dotnet-version: |
          5.x
          3.1.x
