name: Testing multiple environment 

on:
  workflow_dispatch:

jobs:
  dev-job:
    runs-on: ubuntu-latest
    environment: DEV
    steps:
    - uses: actions/checkout@v2
      run: echo "from dev environemnt"
  qa-job:
    runs-on: ubuntu-latest
    environment: QA
    steps:
    - uses: actions/checkout@v2
      run: echo "from qa environemnt"
    
