name: Testing  

on:
  workflow_dispatch:
    inputs:
      Deploy-to:
        type: environment
        description: Select the environment
        required: true  
env:
  name: ${{vars.MY_NAME}}
  uid: ${{ secrets.UID }}
  bottle: ${{vars.BOTTLE}}
jobs:
  prints:
    if: ${{ inputs.Deploy-to == 'DEV' }}
    runs-on: ubuntu-latest
    environment: ${{ inputs.Deploy-to }}
    steps:
    - uses: actions/checkout@v2
      name: printing env message
    - run: mvn deploy 
  print2:
    if: ${{ always() }}
    needs: [prints]
    runs-on: ubuntu-latest
    environment: ${{ inputs.Deploy-to }}
    steps:
    - run: echo "chandra"
    
