name: Testing  

on:
  workflow_call:
  workflow_dispatch:
    inputs:
      Deploy-to:
        type: environment
        description: Select the environment
        required: true  
      Name:
        description: Please provide the name
        required: true 
env:
  name: ${{vars.MY_NAME}}
  uid: ${{ secrets.UID }}
  bottle: ${{vars.BOTTLE}}
jobs:
  prints:
    if: ${{ inputs.Deploy-to == 'DEV' || inputs.Deploy-to == 'QA' }}
    runs-on: ubuntu-latest
    environment: ${{ inputs.Deploy-to }}
    steps:
    - uses: actions/checkout@v2
      name: printing env message
    - run: ${{ inputs.Name }}
  print2:
    if: ${{ failure() || success() }}
    needs: [prints]
    runs-on: ubuntu-latest
    environment: ${{ inputs.Deploy-to }}
    steps:
    - run: echo "chandra"
    
