name: Testing multiple environment 

on:
  workflow_dispatch:
env:
  name: ${{vars.MY_NAME}}
jobs:
  dev-job:
    runs-on: ubuntu-latest
    environment: DEV
    steps:
    - uses: actions/checkout@v2
      name: printing env message
    - run: |
        echo "from dev environemnt"
        echo $name
  qa-job:
    needs: dev-job
    runs-on: ubuntu-latest
    environment: QA
    steps:
    - uses: actions/checkout@v2
    - run: echo "from qa environemnt"
    
