name: Testing  

on:
  workflow_dispatch:
    inputs:
      Deploy-to:
        type: environment
        description: Select the environment
        required: true  
env:
  name: ${{vars.MY_NAME}}
  uid: ${{ secrets.UID }}
  bottle: ${{vars.BOTTLE}}
jobs:
  prints:
    runs-on: ubuntu-latest
    environment: ${{ inputs.Deploy-to }}
    steps:
    - uses: actions/checkout@v2
      name: printing env message
    - run: mvn deploy  
      name: print names
    - uses: actions/setup-node@v1
      if: ${{inputs.Deploy-to =='DEV'}}
      with:
        node-version: '10.x'
        
    - run: echo ${{env.name}}
      name: second name
    - run: echo ${{env.name}}
      name: third name
    - run: echo ${{env.name}}
      name: fourth name
    - run: echo ${{github.ref_name}}
  devjob:
    needs: prints
    runs-on: ubuntu-latest
    environment: ${{ inputs.Deploy-to }}
    if: ${{inputs.Deploy-to =='DEV' || inputs.Deploy-to =='QA'}}
    #uses: ./.github/workflows/dotnet-test.yml
    steps:
      - name: The job has failed
        if: ${{ failure() }}
      - uses: actions/checkout@v2
        name: test bottle names
      - run: ${{ env.bottle }}
