name: Testing multiple environment 

on:
  workflow_dispatch:
    inputs:
      environment-value:
        type: environment
        description: Select the environment
        
env:
  name: ${{vars.MY_NAME}}
  uid: ${{ secrets.UID }}
jobs:
  job:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment-value }}
    steps:
    - uses: actions/checkout@v2
      name: printing env message
    - run: |
        echo "from ${{ inputs.value }} environemnt"
        echo $name
        echo $uid

    
