name : Multi-version Node-js environment
on : 
  push : 
    branches : ["master"]
  
  pull_request : 
    branches : ["master"]  
jobs:
  setup-node-environment:
    runs-on : ubuntu-latest
    steps :
     - uses : actions/checkout@v3
     - name : Setting up node js on ubuntu
     - uses : actions/setup-node@v3
     - run : |
        echo "hello abc"
      
