name: PR Raise

on:
  push: 
    branches: ['testing']
jobs:
  prints:
    runs-on: ubuntu-latest

    steps:
    - name: Raise PR
      run: |
        gh api \
        --method POST \
        -H "Accept: application/vnd.github+json" \
        -H "X-GitHub-Api-Version: 2022-11-28" \
        repos/chandra-stack/Multi-version-node-js/pulls \
        -f "title=Amazing new feature" -f "body=Please pull these awesome changes in!" -f "head=testing" -f "base=release/1.0"
      env:
          GH_TOKEN: ${{ secrets.token }}

        




    
