name: PR Raise

on:
  push: 
    branches: ['testing']
jobs:
  prints:
    runs-on: windows-latest

    steps:
    - name: Raise PR
      run: |
        curl -L -X POST -H "Accept: application/vnd.github+json " -H "Authorization: Bearer ${{ secrets.token}}" -H "X-GitHub-Api-Version: 2022-11-28" https://api.github.com/repos/chandra-stack/Multi-version-node-js/pulls -d '{"title":"Amazing new feature","body":"Please pull these awesome changes in!","head":${{ github.ref_name }},"base":"release/1.0"}'
        


        




    
